### ISSUE TITLE
After creating a new role definition, the id is not correct (contains encoded chars)

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi-azure-nextgen#211]
I created a new RoleDefinition with following code:

```ts
import * as random from "@pulumi/random";
import * as azure_nextgen_authorization_v20150701 from "@pulumi/azure-nextgen/authorization/v20150701";

const uuid = new random.RandomUuid("rd-uuid")
const managementGroupId = "/providers/Microsoft.Management/managementGroups/mg-prod/"
const roleDefinition = new azure_nextgen_authorization_v20150701.RoleDefinition("rd-custom-role", {
    roleDefinitionId: uuid.result,
    roleName: `custom-role`, 
    assignableScopes: [managementGroupId],
    permissions: [{
        actions: [
            "*",
        ],
        notActions: [
        ],
    }],    
    scope: managementGroupId
});
```

After creation, the resource `id` is not valid. The value is `/%2Fproviders%2FMicrosoft.Management%2FmanagementGroups%2Fmg-cloud-sandbox/providers/Microsoft.Authorization/roleDefinitions/63601e5a-ef41-78e2-f098-31f92df98b7`"

Note that `id` is also invalid when the scope is a subscription (more usual). In this case, the `id` is `/%2Fsubscriptions%2Fxxxx-xxxx-xxxx-xxxx-xxxx/providers/Microsoft.Authorization/roleDefinitions/7c78664f-3dbc-4fd4-05bb-26a96d0ba29a`

I tried creating the same with ARM, and the returned `id` is correct : 
```json
{
  "id": "/providers/Microsoft.Management/managementGroups/mg-prod/providers/Microsoft.Resources/deployments/arm-definition",
  "location": "francecentral",
  "name": "arm-definition",
  "properties": {
    "correlationId": "3331deef-1ada-4e6b-9711-f6c56c69ebfb",
    "debugSetting": null,
    "dependencies": [],
    "duration": "PT3.7174652S",
    "error": null,
    "mode": "Incremental",
    "onErrorDeployment": null,
    "outputResources": [
      {
        "id": "/providers/Microsoft.Management/managementGroups/mg-cloud-sandbox/providers/Microsoft.Authorization/roleDefinitions/2681bc39-96be-5b70-98e1-e65941ce719d"
      }
    ],
...
```

**Comment by boillodmanuel** [comment]
I can attached corresponding ARM if required

**Comment by boillodmanuel** [comment]
Currently I use this workaround function:


```ts
/**
 * Apply fix for https://github.com/pulumi/pulumi-azure-nextgen/issues/211
 */
function fixCustomRoleId(id: string): string {
    return id
        .replace(/\/%2F/, '/') // replace first occurrence where "/" and "%2F" are joined
        .replace(/%2F/g, '/')  // replace other occurrences of "%2F"
}

const roleDefinition = new azure_nextgen_authorization_v20150701.RoleDefinition(...)

const rauuid = new random.RandomUuid("ra-uuid")
const roleAssignment = new azure_nextgen_authorization_v20150701.RoleAssignment("ra", {
    properties: {
        principalId: "<ID>",
        roleDefinitionId: roleDefinition.id.apply(fixCustomRoleId),
    },
    roleAssignmentName: rauuid.result,
    scope: "<SCOPE>",
});

```

**Comment by boillodmanuel** [comment]
If it can help, the stack export give:

```json
{
    "urn": "urn:pulumi:sandbox::foundations::azure-nextgen:authorization/v20150701:RoleDefinition::rd-custom-role",
    "custom": true,
    "id": "/%2Fproviders%2FMicrosoft.Management%2FmanagementGroups%2Fmg-prod/providers/Microsoft.Authorization/roleDefinitions/63601e5a-ef41-78e2-f098-31f92df98b74",
    "type": "azure-nextgen:authorization/v20150701:RoleDefinition",
    "inputs": {
        "assignableScopes": [
            "/providers/Microsoft.Management/managementGroups/mg-prod"
        ],
        "description": "Custom Role",
        "permissions": [
            {
                "actions": [
                    "*"
                ],
                "notActions": []
            }
        ],
        "roleDefinitionId": "63601e5a-ef41-78e2-f098-31f92df98b74",
        "roleName": "Custom Role",
        "scope": "/providers/Microsoft.Management/managementGroups/mg-prod"
    },
    "outputs": {
        "__inputs": {
            "4dabf18193072939515e22adb298388d": "xxxx",
            "ciphertext": "xxxx"
        },
        "assignableScopes": [
            "/providers/Microsoft.Management/managementGroups/mg-prod"
        ],
        "description": "Custom Role",
        "id": "/providers/Microsoft.Authorization/roleDefinitions/63601e5a-ef41-78e2-f098-31f92df98b74",
        "name": "63601e5a-ef41-78e2-f098-31f92df98b74",
        "permissions": [
            {
                "actions": [
                    "*"
                ],
                "notActions": []
            }
        ],
        "roleName": "Custom Role",
        "type": "Microsoft.Authorization/roleDefinitions"
    },
    "parent": "urn:pulumi:sandbox::foundations::pulumi:pulumi:Stack::foundations-sandbox",
    "dependencies": [
        "urn:pulumi:sandbox::foundations::azure:management/group:Group::mg-prod",
        "urn:pulumi:sandbox::foundations::random:index/randomUuid:RandomUuid::rd-custom-role-uuid"
    ],
    "provider": "urn:pulumi:sandbox::foundations::pulumi:providers:azure-nextgen::default_0_4_0::c96df9e3-422e-4915-a7a9-fcbaa6c0662f",
    "propertyDependencies": {
        "assignableScopes": [
            "urn:pulumi:sandbox::foundations::azure:management/group:Group::mg-prod"
        ],
        "description": null,
        "permissions": null,
        "roleDefinitionId": [
            "urn:pulumi:sandbox::foundations::random:index/randomUuid:RandomUuid::rd-custom-role-uuid"
        ],
        "roleName": null,
        "scope": [
            "urn:pulumi:sandbox::foundations::azure:management/group:Group::mg-prod"
        ]
    },
    "aliases": [
        "urn:pulumi:sandbox::foundations::azure-nextgen:authorization/latest:RoleDefinition::rd-custom-role",
        "urn:pulumi:sandbox::foundations::azure-nextgen:authorization/v20180101preview:RoleDefinition::rd-custom-role"
    ]
},
```

**Comment by mikhailshilkov** [comment]
Thank you for reporting. Do I understand correctly that the resource is created fine but the `id` property is wrong? Your last message shows a valid id `"/providers/Microsoft.Authorization/roleDefinitions/63601e5a-ef41-78e2-f098-31f92df98b74"` - where do you see the wrong one?

**Comment by boillodmanuel** [comment]
In the code, the property `roleDefinition.id` is equals to `/%2Fproviders%2FMicrosoft.Management%2FmanagementGroups%2Fmg-prod/providers/Microsoft.Authorization/roleDefinitions/63601e5a-ef41-78e2-f098-31f92df98b74` (I think it's the pulumi resource id that we can find in the stack export).

I expect it to be the azure id (or at least that the azure id could be retrieved via a property).
The azure id looks like `"/providers/Microsoft.Management/managementGroups/mg-cloud-sandbox/providers/Microsoft.Authorization/roleDefinitions/63601e5a-ef41-78e2-f098-31f92df98b74"`, as you can see in the ARM command output:
```json
"outputResources": [
      {
        "id": "/providers/Microsoft.Management/managementGroups/mg-cloud-sandbox/providers/Microsoft.Authorization/roleDefinitions/63601e5a-ef41-78e2-f098-31f92df98b74"
      }
    ],
```

When I create a RoleAssignment, we need to set the `roleDefinitionId` property. 
**Today I can't get it from the `roleDefinition` resource/variable**.  🤔
```ts
const roleAssignment = new azure_nextgen_authorization_v20150701.RoleAssignment("ra", {
    properties: {
        principalId: "<ID>",
        roleDefinitionId: roleDefinition.id.apply(fixCustomRoleId),
    },
    roleAssignmentName: rauuid.result,
    scope: "<SCOPE>",
});
```

I hope to be clearer now ;)

**Comment by mikhailshilkov** [comment]
Fixed in the next release

**Comment by boillodmanuel** [comment]
I tried the version `0.5.0` and I noticed no change. I still have the same issue.

Note that the resource `id` may be correct, but in this case, I lack a way to get the `role definition id` to be uses in role assignment.

**Comment by mikhailshilkov** [comment]
The fix was for

> the property roleDefinition.id is equals to /%2Fproviders%2FMicrosoft.Management%2FmanagementGroups%2Fmg-prod/providers/Microsoft.Authorization/roleDefinitions/63601e5a-ef41-78e2-f098-31f92df98b74 

for any resource newly created with 0.5.0.

Have you recreated your resource but still seeing an invalid ID?

>  lack a way to get the role definition id to be uses in role assignment.

Not sure I understand... Your original code should now work without `fixCustomRoleId` - if you re-create the role definition.

**Comment by boillodmanuel** [comment]
I didn't recreate the resource from scratch, only a `pulumi update` after having upgraded the dependency. I will try right now.

**Comment by boillodmanuel** [comment]
I deleted all RoleDefinition and RoleAssignment before recreating them again, and I can confirm everything is working 👍👍👍

Doing a whole migration without RBAC downtime is not easy, but it's on my side right now :)
Migration notes for people interested in:
- I first update existing `RoleAssignment` with a built-in role with higher privilege, 
- then delete all the custom role definition, 
- before restoring everything)

Thanks @mikhailshilkov
